<?php

// for php5.6
$finder = PhpCsFixer\Finder::create()
    ->exclude('node_modules')
    ->in(__DIR__);

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules(array(
        '@PSR2'        => true,
        '@Symfony'     => true,
        'array_syntax' => array(
            'syntax' => 'long',
        ),
        'binary_operator_spaces' => array(
            'default' => 'align_single_space_minimal',
        ),
        'blank_line_after_namespace'   => true,
        'blank_line_after_opening_tag' => true,
        'blank_line_before_statement'  => array(
            'statements' => array(
                'break',
                'continue',
                'declare',
                'do',
                'for',
                'foreach',
                'if',
                'include',
                'include_once',
                'require',
                'require_once',
                'return',
                'switch',
                'throw',
                'try',
                'while',
                'break',
                'die',
                'exit',
            ),
        ),
        'braces'           => true,
        'cast_spaces'      => true,
        'class_definition' => array(
            'multiLineExtendsEachSingleLine' => true,
            'singleItemSingleLine'           => true,
        ),
        'combine_consecutive_unsets' => true,
        'concat_space'               => array(
            'spacing' => 'one',
        ),
        'declare_equal_normalize' => array(
            'space' => 'single',
        ),
        'dir_constant'         => true,
        'elseif'               => true,
        'encoding'             => true,
        'ereg_to_preg'         => true,
        'full_opening_tag'     => true,
        'function_declaration' => array(
            'closure_function_spacing' => 'one',
        ),
        'function_to_constant'      => true,
        'function_typehint_space'   => true,
        'single_line_comment_style' => true,
        // 'header_comment' =>
        'include'                     => true,
        'indentation_type'            => true,
        'is_null'                     => true,
        'line_ending'                 => true,
        'linebreak_after_opening_tag' => true,
        'lowercase_cast'              => true,
        'lowercase_constants'         => true,
        'lowercase_keywords'          => true,
        'magic_constant_casing'       => true,
        // 'mb_str_functions' => true,
        'method_argument_space' => array(
            'ensure_fully_multiline'           => true,
            'keep_multiple_spaces_after_comma' => true,
        ),
        'method_separation'                  => true,
        'modernize_types_casting'            => true,
        'native_function_casing'             => true,
        'native_function_invocation'         => true,
        'new_with_braces'                    => true,
        'no_alias_functions'                 => true,
        'no_blank_lines_after_class_opening' => true,
        // 'no_blank_lines_before_namespace' => true,
        'no_closing_tag'                              => true,
        'no_empty_comment'                            => true,
        'no_empty_statement'                          => true,
        'no_extra_consecutive_blank_lines'            => true,
        'no_leading_import_slash'                     => true,
        'no_leading_namespace_whitespace'             => true,
        'no_mixed_echo_print'                         => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_multiline_whitespace_before_semicolons'   => true,
        'no_php4_constructor'                         => true,
        'no_short_bool_cast'                          => true,
        'no_singleline_whitespace_before_semicolons'  => true,
        'no_spaces_after_function_name'               => true,
        'no_spaces_around_offset'                     => true,
        'no_spaces_inside_parenthesis'                => true,
        'no_trailing_comma_in_list_call'              => true,
        'no_trailing_comma_in_singleline_array'       => true,
        'no_trailing_whitespace'                      => true,
        'no_trailing_whitespace_in_comment'           => true,
        'no_unneeded_control_parentheses'             => true,
        // 'no_unreachable_default_argument_value' => true,
        'no_unused_imports'                   => true,
        'no_useless_else'                     => true,
        'no_useless_return'                   => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_whitespace_in_blank_line'         => true,
        'non_printable_character'             => true,
        'normalize_index_brace'               => true,
        'not_operator_with_space'             => true,
        'not_operator_with_successor_space'   => true,
        'object_operator_without_whitespace'  => true,
        'ordered_class_elements'              => array(
            'order' => array('use_trait', 'constant_public', 'constant_protected', 'constant_private', 'property_public', 'property_protected', 'property_private', 'construct', 'destruct', 'magic', 'phpunit', 'method_public', 'method_protected', 'method_private'),
        ),
        'ordered_imports'         => true,
        'pow_to_exponentiation'   => false,
        'pre_increment'           => true,
        'return_type_declaration' => true,
        'short_scalar_cast'       => true,
        // 'simplified_null_return' => true,
        'single_blank_line_at_eof'           => true,
        'single_blank_line_before_namespace' => true,
        'single_class_element_per_statement' => true,
        'single_import_per_statement'        => true,
        'single_line_after_imports'          => true,
        'single_quote'                       => true,
        'space_after_semicolon'              => true,
        'standardize_not_equals'             => true,
        // 'strict_comparison' => true,
        'switch_case_semicolon_to_colon'    => true,
        'switch_case_space'                 => true,
        'ternary_operator_spaces'           => true,
        'trailing_comma_in_multiline_array' => true,
        'trim_array_spaces'                 => true,
        'unary_operator_spaces'             => true,
        'whitespace_after_comma_in_array'   => true,
    ))
    ->setFinder($finder);
