<?php

declare(strict_types=1);

$finder = PhpCsFixer\Finder::create()
    ->exclude(__DIR__ . '/dist')
    ->exclude(__DIR__ . '/.tmp')
    ->exclude(__DIR__ . '/node_modules')
    ->notPath(__DIR__ . '/functions.php')
    ->in(__DIR__);

return (new PhpCsFixer\Config())
    ->setIndent('    ')
    ->setRiskyAllowed(true)
    ->setLineEnding("\n")
    ->setUsingCache(false)
    ->setRules(array(
        '@PHP70Migration'              => false,
        '@PHP71Migration'              => false,
        '@PSR2'                        => true,
        '@Symfony'                     => true,
        '@Symfony:risky'               => true,
        'array_indentation'            => true,
        'array_syntax'                 => array('syntax' => 'long'),
        'backtick_to_shell_exec'       => true,
        'binary_operator_spaces'       => array('default' => 'align_single_space_minimal'),
        'blank_line_after_namespace'   => true,
        'blank_line_after_opening_tag' => true,
        'blank_line_before_statement'  => array(
            'statements' => array(
                'break',
                'case',
                'continue',
                'declare',
                'default',
                'do',
                'exit',
                'for',
                'foreach',
                'goto',
                'if',
                'include',
                'include_once',
                'require',
                'require_once',
                'return',
                'switch',
                'throw',
                'try',
                'while',
                'yield',
                'yield_from',
            ),
        ),
        'braces'                      => true,
        'cast_spaces'                 => true,
        'class_attributes_separation' => true,
        'class_definition'            => array(
            'multi_line_extends_each_single_line' => true,
            'single_item_single_line'             => true,
        ),
        'combine_consecutive_issets'   => true,
        'combine_consecutive_unsets'   => true,
        'combine_nested_dirname'       => true,
        'compact_nullable_typehint'    => true,
        'concat_space'                 => array('spacing' => 'one'),
        'date_time_immutable'          => true,
        'declare_equal_normalize'      => true,
        'declare_strict_types'         => false,
        'dir_constant'                 => true,
        'elseif'                       => true,
        'encoding'                     => true,
        'ereg_to_preg'                 => true,
        'escape_implicit_backslashes'  => array('single_quoted' => true),
        'explicit_indirect_variable'   => true,
        'explicit_string_variable'     => true,
        'fopen_flag_order'             => true,
        'fopen_flags'                  => true,
        'full_opening_tag'             => true,
        'fully_qualified_strict_types' => true,
        'function_declaration'         => true,
        'function_to_constant'         => true,
        'function_typehint_space'      => true,
        'global_namespace_import'      => true,
        // // 'heredoc_indentation'                         => false,
        'heredoc_to_nowdoc'                           => true,
        'implode_call'                                => true,
        'include'                                     => true,
        'increment_style'                             => true,
        'indentation_type'                            => true,
        'is_null'                                     => true,
        'line_ending'                                 => true,
        'linebreak_after_opening_tag'                 => true,
        'list_syntax'                                 => array('syntax' => 'short'),
        'logical_operators'                           => true,
        'lowercase_cast'                              => true,
        'lowercase_keywords'                          => true,
        'lowercase_static_reference'                  => true,
        'magic_constant_casing'                       => true,
        'magic_method_casing'                         => true,
        'mb_str_functions'                            => false,
        'method_argument_space'                       => true,
        'method_chaining_indentation'                 => true,
        'modernize_types_casting'                     => true,
        'multiline_comment_opening_closing'           => true,
        'multiline_whitespace_before_semicolons'      => true,
        'native_constant_invocation'                  => true,
        'native_function_casing'                      => true,
        'native_function_invocation'                  => true,
        'native_function_type_declaration_casing'     => true,
        'new_with_braces'                             => true,
        'no_alias_functions'                          => true,
        'no_alternative_syntax'                       => true,
        'no_binary_string'                            => true,
        'no_blank_lines_after_class_opening'          => true,
        'no_blank_lines_after_phpdoc'                 => true,
        'no_break_comment'                            => true,
        'no_closing_tag'                              => true,
        'no_empty_comment'                            => true,
        'no_empty_statement'                          => true,
        'no_empty_phpdoc'                             => true,
        'no_extra_blank_lines'                        => true,
        'no_leading_import_slash'                     => true,
        'no_leading_namespace_whitespace'             => true,
        'no_mixed_echo_print'                         => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_null_property_initialization'             => true,
        'no_php4_constructor'                         => true,
        'no_short_bool_cast'                          => true,
        'echo_tag_syntax'                             => false,
        'no_singleline_whitespace_before_semicolons'  => true,
        'no_spaces_after_function_name'               => true,
        'no_spaces_inside_parenthesis'                => true,
        'no_superfluous_elseif'                       => true,
        'no_superfluous_phpdoc_tags'                  => true,
        'no_trailing_comma_in_list_call'              => true,
        'no_trailing_comma_in_singleline_array'       => true,
        'no_trailing_whitespace'                      => true,
        'no_trailing_whitespace_in_comment'           => true,
        'no_unneeded_curly_braces'                    => true,
        'no_unneeded_final_method'                    => true,
        'no_unreachable_default_argument_value'       => true,
        'no_unset_cast'                               => true,
        // 'no_unset_on_property'=> true,
        'no_unused_imports'                                => true,
        'no_useless_else'                                  => true,
        'no_useless_return'                                => true,
        'no_whitespace_before_comma_in_array'              => true,
        'no_whitespace_in_blank_line'                      => true,
        'non_printable_character'                          => true,
        'normalize_index_brace'                            => true,
        'not_operator_with_space'                          => true,
        'not_operator_with_successor_space'                => true,
        'nullable_type_declaration_for_default_null_value' => false,
        'object_operator_without_whitespace'               => true,
        'ordered_imports'                                  => true,
        'ordered_interfaces'                               => true,
        'pow_to_exponentiation'                            => false,
        'psr_autoloading'                                  => true,
        'return_assignment'                                => true,
        'return_type_declaration'                          => true,
        'self_accessor'                                    => false,
        'self_static_accessor'                             => false,
        'semicolon_after_instruction'                      => true,
        'set_type_to_cast'                                 => true,
        'short_scalar_cast'                                => true,
        'simple_to_complex_string_variable'                => true,
        'simplified_null_return'                           => true,
        'single_blank_line_at_eof'                         => true,
        'single_blank_line_before_namespace'               => true,
        'single_import_per_statement'                      => true,
        'single_line_after_imports'                        => true,
        'single_line_comment_style'                        => true,
        'single_line_throw'                                => true,
        'single_quote'                                     => true,
        'single_trait_insert_per_statement'                => true,
        'space_after_semicolon'                            => array('remove_in_empty_for_expressions' => true),
        'standardize_increment'                            => true,
        'standardize_not_equals'                           => true,
        'strict_comparison'                                => true,
        'strict_param'                                     => true,
        'switch_case_semicolon_to_colon'                   => true,
        'switch_case_space'                                => true,
        'ternary_operator_spaces'                          => true,
        'ternary_to_null_coalescing'                       => false,
        'trailing_comma_in_multiline'                      => true,
        'trim_array_spaces'                                => true,
        'unary_operator_spaces'                            => true,
        'void_return'                                      => false,
        'whitespace_after_comma_in_array'                  => true,
        'yoda_style'                                       => true,
        'visibility_required'                              => true,
        'constant_case'                                    => true,
        'ordered_class_elements'                           => true,
        'single_class_element_per_statement'               => true,
    ))
    ->setFinder($finder);
