import { darken, lighten, rgba } from 'polished'
import { gettext } from '../../Language'
import { ColorSchemeProps } from '../typings'
const light = '#ccc'
const dark = '#000'
const topDarkBottomLight = `linear-gradient(#000, #111)`
export const colorSchemeDark: ColorSchemeProps = {
  name: gettext('Dark'),
  isDark: true,
  color: `linear-gradient(${rgba(light, 0.3)}, ${rgba(dark, 0.9)})`,
  fg: dark,
  bg: light,
  'selection.fg': light,
  'selection.bg': rgba(dark, 0.95),
  'html.bg': dark,
  'body.fg': light,
  'body.bg': dark,
  'a.fg': light,
  'app.border': dark,
  'app.fg': light,
  'app.bg': '#222',
  'title.fg': light,
  'title.bg': dark,
  'title.boxShadow': `0 1px 0 ${rgba(light, 0.1)}`,
  'sysLoad.fg': light,
  'sysLoad.bg': dark,
  'card.border': rgba('#000', 0.5),
  'card.fg': light,
  'card.bg': '#333',
  'card.hover.bg': `linear-gradient(to right, transparent, ${rgba(
    '#000',
    0.5,
  )}, transparent)`,
  'card.boxShadow': `inset 0 0 0 1px #000`,
  'card.legend.fg': light,
  'card.legend.bg': topDarkBottomLight,
  'card.des.fg': light,
  'card.des.bg': rgba('#000', 0.3),
  'card.title.fg': light,
  'progress.fg': light,
  'progress.bg': topDarkBottomLight,
  'progress.value.fg': light,
  'progress.value.bg': '#0c0',
  'progress.value.after.bg': `linear-gradient(${[
    rgba('#fff', 0.2),
    'transparent',
  ].join(',')})`,
  'progress.value.before.bg': `linear-gradient(to right, ${[
    rgba('#fff', 0.1),
    rgba('#fff', 0.2),
    rgba('#fff', 0.1),
  ].join(',')})`,
  'network.stats.upload': lighten(0.2, '#c24b00'),
  'network.stats.download': lighten(0.2, '#007400'),
  'network.node.fg': light,
  'network.node.bg': '#252525',
  'network.node.border': dark,
  'network.node.row.bg': `linear-gradient(to right, ${[
    'transparent',
    rgba('#000', 0.5),
    'transparent',
  ].join(',')})`,
  'ping.button.fg': light,
  'ping.button.bg': dark,
  'ping.result.fg': light,
  'ping.result.bg': dark,
  'status.success.fg': light,
  'status.success.bg': `linear-gradient(${darken(0.25, '#00e800')}, ${darken(
    0.2,
    '#00e800',
  )})`,
  'status.error.fg': light,
  'status.error.bg': `linear-gradient(${darken(0.45, '#b9b9b9')}, ${darken(
    0.4,
    '#b9b9b9',
  )})`,
  'search.fg': light,
  'search.bg': rgba(dark, 0.1),
  'search.hover.fg': light,
  'search.hover.bg': rgba(dark, 0.3),
  'benchmark.ruby.fg': dark,
  'benchmark.ruby.bg': rgba(dark, 0.1),
  'footer.fg': light,
  'footer.bg': dark,
  'nav.fg': light,
  'nav.bg': dark,
  'nav.hover.fg': light,
  'nav.hover.bg': `linear-gradient(${[
    lighten(0.15, dark),
    lighten(0.05, dark),
  ].join(',')})`,
  'nav.active.fg': light,
  'nav.active.bg': `linear-gradient(${[
    lighten(0.3, dark),
    lighten(0.1, dark),
  ].join(',')})`,
  'nav.border': rgba(light, 0.1),
  'starMe.fg': darken(0.1, light),
  'starMe.bg': dark,
  'starMe.hover.fg': light,
  'starMe.hover.bg': dark,
  'toast.fg': light,
  'toast.bg': dark,
}
