import { gettext } from '@/Language/src'
import { darken, lighten, rgba } from 'polished'
import { colorSchemeProps } from '../typings'
const light = '#f8f8f8'
const dark = '#333'
const topDarkBottomLight = `linear-gradient(#282828, ${lighten(0.05, dark)})`
export const colorSchemeDefault: colorSchemeProps = {
  name: gettext('Default'),
  isDark: false,
  color: `linear-gradient(${rgba(dark, 0.9)}, ${rgba(light, 0.5)})`,
  fg: dark,
  bg: light,
  'selection.fg': light,
  'selection.bg': rgba(dark, 0.95),
  'html.bg': dark,
  'body.fg': dark,
  'body.bg': dark,
  'a.fg': dark,
  'app.border': dark,
  'app.fg': dark,
  'app.bg': light,
  'title.fg': light,
  'title.bg': dark,
  'title.boxShadow': `0 1px 0 #000`,
  'sysLoad.fg': light,
  'sysLoad.bg': dark,
  'card.border': rgba(dark, 0.1),
  'card.fg': dark,
  'card.bg': rgba(dark, 0.03),
  'card.hover.bg': `linear-gradient(to right, transparent, ${rgba(
    '#000',
    0.1
  )}, transparent)`,
  'card.boxShadow': [
    `0 -1px 0 ${rgba(dark, 0.3)}`,
    `inset 0 1px 0 #fff`,
    `inset 0 -1px 0 ${rgba(dark, 0.3)}`,
    `0 1px 0 #fff`,
  ].join(','),
  'card.legend.fg': light,
  'card.legend.bg': topDarkBottomLight,
  'card.title.fg': dark,
  'progress.fg': light,
  'progress.bg': topDarkBottomLight,
  'progress.value.fg': light,
  'progress.value.bg': '#0c0',
  'progress.value.after.bg': `linear-gradient(${[
    rgba('#fff', 0.45),
    'transparent',
  ].join(',')})`,
  'progress.value.before.bg': `linear-gradient(to right, ${[
    rgba('#fff', 0.1),
    rgba('#fff', 0.95),
    rgba('#fff', 0.1),
  ].join(',')})`,
  'network.stats.upload': '#c24b00',
  'network.stats.download': '#007400',
  'network.node.fg': dark,
  'network.node.bg': '#373c381a',
  'network.node.border': '#373c381a',
  'network.node.row.bg':
    'linear-gradient(to right, transparent, #ffffffe6, transparent)',
  'ping.button.fg': light,
  'ping.button.bg': dark,
  'ping.result.fg': light,
  'ping.result.bg': dark,
  'status.success.fg': light,
  'status.success.bg': `linear-gradient(${darken(0.15, '#00e800')}, #00e800)`,
  'status.error.fg': light,
  'status.error.bg': `linear-gradient(${darken(0.25, '#b9b9b9')}, #b9b9b9)`,
  'search.fg': dark,
  'search.bg': rgba(dark, 0.1),
  'search.hover.fg': light,
  'search.hover.bg': rgba(dark, 0.3),
  'benchmark.ruby.fg': dark,
  'benchmark.ruby.bg': rgba(dark, 0.1),
  'footer.fg': light,
  'footer.bg': dark,
  'nav.fg': light,
  'nav.bg': dark,
  'nav.hover.fg': light,
  'nav.hover.bg': `linear-gradient(${rgba(light, 0.25)}, ${rgba(light, 0.1)})`,
  'nav.active.fg': dark,
  'nav.active.bg': `linear-gradient(${light}, ${darken(0.15, light)})`,
  'nav.border': rgba(light, 0.1),
  'starMe.fg': darken(0.1, light),
  'starMe.bg': dark,
  'starMe.hover.fg': light,
  'starMe.hover.bg': dark,
  'toast.fg': light,
  'toast.bg': dark,
}
