<?php

namespace InnStudio\Prober\Components\Rest;

final class StatusCode
{
    const CONTINUE = 100;

    const SWITCHING_PROTOCOLS = 101;

    const PROCESSING = 102; // WEBDAV;_RFC_2518

    const OK = 200;

    const CREATED = 201;

    const ACCEPTED = 202;

    const NON_AUTHORITATIVE_INFORMATION = 203; // SINCE_HTTP/1.1

    const NO_CONTENT = 204;

    const RESET_CONTENT = 205;

    const PARTIAL_CONTENT = 206;

    const MULTI_STATUS = 207; // WEBDAV;_RFC_4918

    const ALREADY_REPORTED = 208; // WEBDAV;_RFC_5842

    const IM_USED = 226; // RFC_3229

    const MULTIPLE_CHOICES = 300;

    const MOVED_PERMANENTLY = 301;

    const FOUND = 302;

    const SEE_OTHER = 303; // SINCE_HTTP/1.1

    const NOT_MODIFIED = 304;

    const USE_PROXY = 305; // SINCE_HTTP/1.1

    const SWITCH_PROXY = 306;

    const TEMPORARY_REDIRECT = 307; // SINCE_HTTP/1.1

    const PERMANENT_REDIRECT = 308; // APPROVED_AS_EXPERIMENTAL_RFC

    const BAD_REQUEST = 400;

    const UNAUTHORIZED = 401;

    const PAYMENT_REQUIRED = 402;

    const FORBIDDEN = 403;

    const NOT_FOUND = 404;

    const METHOD_NOT_ALLOWED = 405;

    const NOT_ACCEPTABLE = 406;

    const PROXY_AUTHENTICATION_REQUIRED = 407;

    const REQUEST_TIMEOUT = 408;

    const CONFLICT = 409;

    const GONE = 410;

    const LENGTH_REQUIRED = 411;

    const PRECONDITION_FAILED = 412;

    const REQUEST_ENTITY_TOO_LARGE = 413;

    const REQUEST_URI_TOO_LONG = 414;

    const UNSUPPORTED_MEDIA_TYPE = 415;

    const REQUESTED_RANGE_NOT_SATISFIABLE = 416;

    const EXPECTATION_FAILED = 417;

    const I_AM_A_TEAPOT = 418;

    const AUTHENTICATION_TIMEOUT = 419; // NOT_IN_RFC_2616

    const ENHANCE_YOUR_CALM = 420; // TWITTER

    const METHOD_FAILURE = 420; // SPRING_FRAMEWORK

    const UNPROCESSABLE_ENTITY = 422; // WEBDAV;_RFC_4918

    const LOCKED = 423; // WEBDAV;_RFC_4918

    const FAILED_DEPENDENCY = 424; // WEBDAV

    const UNORDERED_COLLECTION = 425; // INTERNET_DRAFT

    const UPGRADE_REQUIRED = 426; // RFC_2817

    const PRECONDITION_REQUIRED = 428; // RFC_6585

    const TOO_MANY_REQUESTS = 429; // RFC_6585

    const REQUEST_HEADER_FIELDS_TOO_LARGE = 431; // RFC_6585

    const NO_RESPONSE = 444; // NGINX

    const RETRY_WITH = 449; // MICROSOFT

    const BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS = 450; // MICROSOFT

    const REDIRECT = 451; // MICROSOFT

    const UNAVAILABLE_FOR_LEGAL_REASONS = 451; // INTERNET_DRAFT

    const REQUEST_HEADER_TOO_LARGE = 494; // NGINX

    const CERT_ERROR = 495; // NGINX

    const NO_CERT = 496; // NGINX

    const HTTP_TO_HTTPS = 497; // NGINX

    const CLIENT_CLOSED_REQUEST = 499; // NGINX

    const INTERNAL_SERVER_ERROR = 500;

    const NOT_IMPLEMENTED = 501;

    const BAD_GATEWAY = 502;

    const SERVICE_UNAVAILABLE = 503;

    const GATEWAY_TIMEOUT = 504;

    const HTTP_VERSION_NOT_SUPPORTED = 505;

    const VARIANT_ALSO_NEGOTIATES = 506; // RFC_2295

    const INSUFFICIENT_STORAGE = 507; // WEBDAV;_RFC_4918

    const LOOP_DETECTED = 508; // WEBDAV;_RFC_5842

    const BANDWIDTH_LIMIT_EXCEEDED = 509; // APACHE_BW/LIMITED_EXTENSION

    const NOT_EXTENDED = 510; // RFC_2774

    const NETWORK_AUTHENTICATION_REQUIRED = 511; // RFC_6585

    const NETWORK_READ_TIMEOUT_ERROR = 598; // UNKNOWN

    const NETWORK_CONNECT_TIMEOUT_ERROR = 599; // Unknown
}
